# Generated by Django 3.1 on 2022-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_auto_20220219_0018'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='mystore.Variation'),
        ),
    ]
