# Generated by Django 3.1 on 2022-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20220219_1643'),
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='mystore.Variation'),
        ),
    ]
