# Generated by Django 3.1 on 2022-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_auto_20220219_0018'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
